### ISSUE TITLE
Enhancement - Helper 

### ISSUE THREAD

**Issue by ClaesFredo** [zhdk/leihs#87]
Hi

The Helper is, well, very helpful. My database contains about 1100 items and is still growing. 

It has happened more than once that I would have to edit some fields in the whole database. It can be done but requires time and patience. 

In these circumstances, it would be useful to be able to upload a list of items to be updated to the helper and let the helper chew its way through this list.  

The suggestion therefore is to add the possibility to read a list with a string of items to be updated. 

Sincerely
Claes

**Comment by psy-q** [comment]
There is something along those lines coming in the form of a CSV import. The goal is that you can export your inventory to any tool that understands CSV (LibreOffice Calc, OpenOffice Calc, Microsoft Excel, Excel Online, Google Docs...) and edit it there. When you're done, upload the file and anything that can be changed and still is valid will be changed.

Doing something like this properly is quite time intensive, that's why so far we only have a CSV import feature that does not update existing inventory, just import new stuff. So I'd suggest that you wait for the CSV import/update feature to be finished and try that, I wouldn't add this in with the helper.

The helper is more meant to be used with series of items scanned using a barcode scanner. Full-scale batch editing is still some years away, unless someone contributes that feature :)

Feel free to open a new issue if the CSV import feature doesn't fulfill this.
