### ISSUE TITLE
Enhancement - Templates - Items

### ISSUE THREAD

**Issue by ClaesFredo** [zhdk/leihs#89]
When making a Template, it would be useful to be able to select specific Items and in doing so reserve a group of items rather than a group of models. 

The suggestion is to add the possibility to incorporate Items as an option for the Template function. 

Sincerely
Claes

**Comment by psy-q** [comment]
That won't be possible since the way leihs works, you never reserve a specific item, always a model.

The reason is that usually there are more than one of one model, since many inventory pools buy multiple copies of each item so that they can juggle things around if one breaks, etc.

Implementing this directly would clash immensely with the way the system works, since availability calculations, the order process, the approval process and many things in between would be affected.

I'm closing this for that reason -- not because it's a bad idea, just because it doesn't fit with the core of the system.
